#!./!applay_sql_2_local_db_MICHURINO.sh -W

DROP SCHEMA "m" CASCADE;
CREATE SCHEMA "m";
REVOKE ALL ON SCHEMA "m" FROM PUBLIC;
REVOKE ALL ON SCHEMA "m" FROM postgres;
REVOKE ALL ON SCHEMA "m" FROM site;
GRANT ALL ON SCHEMA "m" TO postgres;
GRANT ALL ON SCHEMA "m" TO site;
